// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateMembers implements pgx.CopyFromSource.
type iteratorForCreateMembers struct {
	rows                 []CreateMembersParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateMembers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateMembers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].GroupID,
		r.rows[0].Name,
	}, nil
}

func (r iteratorForCreateMembers) Err() error {
	return nil
}

func (q *Queries) CreateMembers(ctx context.Context, arg []CreateMembersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"members"}, []string{"group_id", "name"}, &iteratorForCreateMembers{rows: arg})
}
