// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package sqlc

type CreateMembersParams struct {
	GroupID int64  `json:"group_id"`
	Name    string `json:"name"`
}
