-- Modify "groups" table
ALTER TABLE "groups" ALTER COLUMN "uid" SET DEFAULT gen_random_uuid();
-- Create trigger "on_update_time_members"
CREATE TRIGGER "on_update_time_members" BEFORE UPDATE ON "groups" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
-- Create "members" table
CREATE TABLE "members" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "group_id" bigint NOT NULL,
  "name" character varying(10) NOT NULL DEFAULT '',
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_members_group_id_name" UNIQUE ("group_id", "name"),
  CONSTRAINT "fk_members_group_id" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
