CREATE OR REPLACE FUNCTION update_updated_at_column()returns TRIGGER AS
$$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$
language plpgsql;

-- Create "groups" table
CREATE TABLE "groups" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "uid" uuid NOT NULL,
  "name" character varying(100) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_groups_uid" UNIQUE ("uid")
);

-- updated_atの自動更新
CREATE TRIGGER on_update_time_groups BEFORE
UPDATE ON groups FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column ();
