-- Create "rules" table
CREATE TABLE "rules" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "group_id" bigint NOT NULL,
  "mahjong_type" integer NOT NULL DEFAULT 2,
  "initial_points" integer NOT NULL DEFAULT 25,
  "return_points" integer NOT NULL DEFAULT 30,
  "ranking_points_first" integer NOT NULL DEFAULT 20,
  "ranking_points_second" integer NOT NULL DEFAULT 10,
  "ranking_points_third" integer NOT NULL DEFAULT -10,
  "ranking_points_fourth" integer NULL,
  "fractional_calculation" integer NOT NULL DEFAULT 0,
  "use_bust" boolean NOT NULL DEFAULT false,
  "bust_point" integer NULL,
  "use_chip" boolean NOT NULL DEFAULT false,
  "chip_point" integer NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_members_group_id" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "chk_bust_point_if_use_bust" CHECK (((use_bust = true) AND (bust_point IS NOT NULL) AND (bust_point > 0)) OR ((use_bust = false) AND (bust_point IS NULL))),
  CONSTRAINT "chk_chip_point_if_use_chip" CHECK (((use_chip = true) AND (chip_point IS NOT NULL) AND (chip_point > 0)) OR ((use_chip = false) AND (chip_point IS NULL))),
  CONSTRAINT "chk_ranking_points_by_mahjong_type" CHECK (
CASE
    WHEN (mahjong_type = 1) THEN ((ranking_points_fourth IS NULL) AND (((ranking_points_first + ranking_points_second) + ranking_points_third) = 0))
    WHEN (mahjong_type = 2) THEN ((ranking_points_fourth IS NOT NULL) AND ((((ranking_points_first + ranking_points_second) + ranking_points_third) + ranking_points_fourth) = 0))
    ELSE NULL::boolean
END),
  CONSTRAINT "rules_fractional_calculation_check" CHECK (fractional_calculation = ANY (ARRAY[1, 2, 3, 4, 5])),
  CONSTRAINT "rules_initial_points_check" CHECK (initial_points > 0),
  CONSTRAINT "rules_mahjong_type_check" CHECK (mahjong_type = ANY (ARRAY[1, 2])),
  CONSTRAINT "rules_return_points_check" CHECK (return_points > 0)
);
-- Set comment to column: "mahjong_type" on table: "rules"
COMMENT ON COLUMN "rules"."mahjong_type" IS '1: 三麻, 2: 四麻';
-- Set comment to column: "initial_points" on table: "rules"
COMMENT ON COLUMN "rules"."initial_points" IS '持ち点 (単位: 千点)';
-- Set comment to column: "return_points" on table: "rules"
COMMENT ON COLUMN "rules"."return_points" IS '返し点 (単位: 千点)';
-- Set comment to column: "ranking_points_first" on table: "rules"
COMMENT ON COLUMN "rules"."ranking_points_first" IS '1位のウマ';
-- Set comment to column: "ranking_points_second" on table: "rules"
COMMENT ON COLUMN "rules"."ranking_points_second" IS '2位のウマ';
-- Set comment to column: "ranking_points_third" on table: "rules"
COMMENT ON COLUMN "rules"."ranking_points_third" IS '3位のウマ';
-- Set comment to column: "ranking_points_fourth" on table: "rules"
COMMENT ON COLUMN "rules"."ranking_points_fourth" IS '4位のウマ';
-- Set comment to column: "fractional_calculation" on table: "rules"
COMMENT ON COLUMN "rules"."fractional_calculation" IS '1: 切り上げ, 2: 切り捨て, 3: 四捨五入, 4: 10点未満切り上げ, 5: 10点未満切り捨て';
-- Set comment to column: "use_bust" on table: "rules"
COMMENT ON COLUMN "rules"."use_bust" IS '飛び設定';
-- Set comment to column: "bust_point" on table: "rules"
COMMENT ON COLUMN "rules"."bust_point" IS '飛び賞のポイント';
-- Set comment to column: "use_chip" on table: "rules"
COMMENT ON COLUMN "rules"."use_chip" IS 'チップ設定';
-- Set comment to column: "chip_point" on table: "rules"
COMMENT ON COLUMN "rules"."chip_point" IS 'チップのポイント';
-- Enable row-level security for "rules" table
ALTER TABLE "rules" ENABLE ROW LEVEL SECURITY;
-- Create policy "group_policy"
CREATE POLICY "group_policy" ON "rules" AS PERMISSIVE FOR ALL TO PUBLIC USING (group_id = (current_setting('app.group_id'::text))::integer);
-- Create trigger "on_update_time_rules"
CREATE TRIGGER "on_update_time_rules" BEFORE UPDATE ON "rules" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
