-- Create "games" table
CREATE TABLE "games" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "group_id" bigint NOT NULL,
  "note" text NULL,
  "played_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_games_group_id" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON UPDATE CASCADE ON DELETE CASCADE
);
-- Create index "idx_games_group_id" to table: "games"
CREATE INDEX "idx_games_group_id" ON "games" ("group_id");
-- Set comment to column: "note" on table: "games"
COMMENT ON COLUMN "games"."note" IS '対局メモ';
-- Set comment to column: "played_at" on table: "games"
COMMENT ON COLUMN "games"."played_at" IS '対局日時';
-- Enable row-level security for "games" table
ALTER TABLE "games" ENABLE ROW LEVEL SECURITY;
-- Create policy "group_policy"
CREATE POLICY "group_policy" ON "games" AS PERMISSIVE FOR ALL TO PUBLIC USING (group_id = (current_setting('app.group_id'::text))::integer);
-- Create trigger "on_update_time_games"
CREATE TRIGGER "on_update_time_games" BEFORE UPDATE ON "games" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
-- Create "game_rules" table
CREATE TABLE "game_rules" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "game_id" bigint NOT NULL,
  "group_id" bigint NOT NULL,
  "mahjong_type" integer NOT NULL,
  "initial_points" integer NOT NULL,
  "return_points" integer NOT NULL,
  "ranking_points_first" integer NOT NULL,
  "ranking_points_second" integer NOT NULL,
  "ranking_points_third" integer NOT NULL,
  "ranking_points_fourth" integer NULL,
  "fractional_calculation" integer NOT NULL,
  "use_bust" boolean NOT NULL DEFAULT false,
  "bust_point" integer NULL,
  "use_chip" boolean NOT NULL DEFAULT false,
  "chip_point" integer NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_game_rules_game_id" UNIQUE ("game_id"),
  CONSTRAINT "fk_game_rules_game_id" FOREIGN KEY ("game_id") REFERENCES "games" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "fk_game_rules_group_id" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "chk_game_rules_bust_point" CHECK (((use_bust = true) AND (bust_point IS NOT NULL) AND (bust_point > 0)) OR ((use_bust = false) AND (bust_point IS NULL))),
  CONSTRAINT "chk_game_rules_chip_point" CHECK (((use_chip = true) AND (chip_point IS NOT NULL) AND (chip_point > 0)) OR ((use_chip = false) AND (chip_point IS NULL))),
  CONSTRAINT "chk_game_rules_ranking_points" CHECK (
CASE
    WHEN (mahjong_type = 1) THEN ((ranking_points_fourth IS NULL) AND (((ranking_points_first + ranking_points_second) + ranking_points_third) = 0))
    WHEN (mahjong_type = 2) THEN ((ranking_points_fourth IS NOT NULL) AND ((((ranking_points_first + ranking_points_second) + ranking_points_third) + ranking_points_fourth) = 0))
    ELSE NULL::boolean
END),
  CONSTRAINT "game_rules_fractional_calculation_check" CHECK (fractional_calculation = ANY (ARRAY[1, 2, 3, 4, 5])),
  CONSTRAINT "game_rules_initial_points_check" CHECK (initial_points > 0),
  CONSTRAINT "game_rules_mahjong_type_check" CHECK (mahjong_type = ANY (ARRAY[1, 2])),
  CONSTRAINT "game_rules_return_points_check" CHECK (return_points > 0)
);
-- Create index "idx_game_rules_group_id" to table: "game_rules"
CREATE INDEX "idx_game_rules_group_id" ON "game_rules" ("group_id");
-- Set comment to column: "mahjong_type" on table: "game_rules"
COMMENT ON COLUMN "game_rules"."mahjong_type" IS '1: 三麻, 2: 四麻';
-- Set comment to column: "initial_points" on table: "game_rules"
COMMENT ON COLUMN "game_rules"."initial_points" IS '持ち点 (単位: 千点)';
-- Set comment to column: "return_points" on table: "game_rules"
COMMENT ON COLUMN "game_rules"."return_points" IS '返し点 (単位: 千点)';
-- Set comment to column: "ranking_points_first" on table: "game_rules"
COMMENT ON COLUMN "game_rules"."ranking_points_first" IS '1位のウマ';
-- Set comment to column: "ranking_points_second" on table: "game_rules"
COMMENT ON COLUMN "game_rules"."ranking_points_second" IS '2位のウマ';
-- Set comment to column: "ranking_points_third" on table: "game_rules"
COMMENT ON COLUMN "game_rules"."ranking_points_third" IS '3位のウマ';
-- Set comment to column: "ranking_points_fourth" on table: "game_rules"
COMMENT ON COLUMN "game_rules"."ranking_points_fourth" IS '4位のウマ';
-- Set comment to column: "fractional_calculation" on table: "game_rules"
COMMENT ON COLUMN "game_rules"."fractional_calculation" IS '1: 切り上げ, 2: 切り捨て, 3: 四捨五入, 4: 10点未満切り上げ, 5: 10点未満切り捨て';
-- Set comment to column: "use_bust" on table: "game_rules"
COMMENT ON COLUMN "game_rules"."use_bust" IS '飛び設定';
-- Set comment to column: "bust_point" on table: "game_rules"
COMMENT ON COLUMN "game_rules"."bust_point" IS '飛び賞のポイント';
-- Set comment to column: "use_chip" on table: "game_rules"
COMMENT ON COLUMN "game_rules"."use_chip" IS 'チップ設定';
-- Set comment to column: "chip_point" on table: "game_rules"
COMMENT ON COLUMN "game_rules"."chip_point" IS 'チップのポイント';
-- Enable row-level security for "game_rules" table
ALTER TABLE "game_rules" ENABLE ROW LEVEL SECURITY;
-- Create policy "group_policy"
CREATE POLICY "group_policy" ON "game_rules" AS PERMISSIVE FOR ALL TO PUBLIC USING (group_id = (current_setting('app.group_id'::text))::integer);
-- Create trigger "on_update_time_game_rules"
CREATE TRIGGER "on_update_time_game_rules" BEFORE UPDATE ON "game_rules" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
-- Create "game_scores" table
CREATE TABLE "game_scores" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "game_id" bigint NOT NULL,
  "group_id" bigint NOT NULL,
  "member_id" bigint NOT NULL,
  "seat" integer NOT NULL,
  "ranking" integer NOT NULL,
  "raw_score" integer NOT NULL,
  "point" numeric(10,1) NOT NULL,
  "chip_count" integer NULL,
  "is_busted" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "uk_game_scores_game_member" UNIQUE ("game_id", "member_id"),
  CONSTRAINT "uk_game_scores_game_ranking" UNIQUE ("game_id", "ranking"),
  CONSTRAINT "uk_game_scores_game_seat" UNIQUE ("game_id", "seat"),
  CONSTRAINT "fk_game_scores_game_id" FOREIGN KEY ("game_id") REFERENCES "games" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "fk_game_scores_group_id" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "fk_game_scores_member_id" FOREIGN KEY ("member_id") REFERENCES "members" ("id") ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "game_scores_ranking_check" CHECK ((ranking >= 1) AND (ranking <= 4)),
  CONSTRAINT "game_scores_seat_check" CHECK ((seat >= 1) AND (seat <= 4))
);
-- Create index "idx_game_scores_group_id" to table: "game_scores"
CREATE INDEX "idx_game_scores_group_id" ON "game_scores" ("group_id");
-- Create index "idx_game_scores_member_id" to table: "game_scores"
CREATE INDEX "idx_game_scores_member_id" ON "game_scores" ("member_id");
-- Set comment to column: "seat" on table: "game_scores"
COMMENT ON COLUMN "game_scores"."seat" IS '1: 東, 2: 南, 3: 西, 4: 北';
-- Set comment to column: "ranking" on table: "game_scores"
COMMENT ON COLUMN "game_scores"."ranking" IS '順位';
-- Set comment to column: "raw_score" on table: "game_scores"
COMMENT ON COLUMN "game_scores"."raw_score" IS '素点 (100点単位, 例: 32400)';
-- Set comment to column: "point" on table: "game_scores"
COMMENT ON COLUMN "game_scores"."point" IS '計算後のポイント';
-- Set comment to column: "chip_count" on table: "game_scores"
COMMENT ON COLUMN "game_scores"."chip_count" IS 'チップ枚数';
-- Set comment to column: "is_busted" on table: "game_scores"
COMMENT ON COLUMN "game_scores"."is_busted" IS '飛びフラグ';
-- Enable row-level security for "game_scores" table
ALTER TABLE "game_scores" ENABLE ROW LEVEL SECURITY;
-- Create policy "group_policy"
CREATE POLICY "group_policy" ON "game_scores" AS PERMISSIVE FOR ALL TO PUBLIC USING (group_id = (current_setting('app.group_id'::text))::integer);
-- Create trigger "on_update_time_game_scores"
CREATE TRIGGER "on_update_time_game_scores" BEFORE UPDATE ON "game_scores" FOR EACH ROW EXECUTE FUNCTION "update_updated_at_column"();
