// Code generated by govalid; DO NOT EDIT.
package in

import (
	"errors"

	"github.com/okm321/mahking-go/internal/domain"
	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilrules is returned when the rules is nil.
	ErrNilrules = errors.New("input rules is nil")

	// ErrrulesMahjongTypeEnumValidation is the error returned when the value is not in the allowed enum values domain.MahjongTypeThree, domain.MahjongTypeFour.
	ErrrulesMahjongTypeEnumValidation = govaliderrors.ValidationError{Reason: "field MahjongType must be one of domain.MahjongTypeThree, domain.MahjongTypeFour", Path: "rules.MahjongType", Type: "enum"}

	// ErrrulesMahjongTypeRequiredValidation is returned when the MahjongType is required but not provided.
	ErrrulesMahjongTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field MahjongType is required", Path: "rules.MahjongType", Type: "required"}

	// ErrrulesInitialPointsGTEValidation is the error returned when the value of the field is less than 1.
	ErrrulesInitialPointsGTEValidation = govaliderrors.ValidationError{Reason: "field InitialPoints must be greater than or equal to 1", Path: "rules.InitialPoints", Type: "gte"}

	// ErrrulesInitialPointsRequiredValidation is returned when the InitialPoints is required but not provided.
	ErrrulesInitialPointsRequiredValidation = govaliderrors.ValidationError{Reason: "field InitialPoints is required", Path: "rules.InitialPoints", Type: "required"}

	// ErrrulesReturnPointsGTEValidation is the error returned when the value of the field is less than 1.
	ErrrulesReturnPointsGTEValidation = govaliderrors.ValidationError{Reason: "field ReturnPoints must be greater than or equal to 1", Path: "rules.ReturnPoints", Type: "gte"}

	// ErrrulesReturnPointsRequiredValidation is returned when the ReturnPoints is required but not provided.
	ErrrulesReturnPointsRequiredValidation = govaliderrors.ValidationError{Reason: "field ReturnPoints is required", Path: "rules.ReturnPoints", Type: "required"}

	// ErrrulesRankingPointsFirstRequiredValidation is returned when the RankingPointsFirst is required but not provided.
	ErrrulesRankingPointsFirstRequiredValidation = govaliderrors.ValidationError{Reason: "field RankingPointsFirst is required", Path: "rules.RankingPointsFirst", Type: "required"}

	// ErrrulesRankingPointsSecondRequiredValidation is returned when the RankingPointsSecond is required but not provided.
	ErrrulesRankingPointsSecondRequiredValidation = govaliderrors.ValidationError{Reason: "field RankingPointsSecond is required", Path: "rules.RankingPointsSecond", Type: "required"}

	// ErrrulesRankingPointsThirdRequiredValidation is returned when the RankingPointsThird is required but not provided.
	ErrrulesRankingPointsThirdRequiredValidation = govaliderrors.ValidationError{Reason: "field RankingPointsThird is required", Path: "rules.RankingPointsThird", Type: "required"}

	// ErrrulesRankingPointsFourCELValidation is the error returned when the CEL expression evaluation fails.
	ErrrulesRankingPointsFourCELValidation = govaliderrors.ValidationError{Reason: "field RankingPointsFour failed CEL validation: this.MahjongType != 2 || value.Valid", Path: "rules.RankingPointsFour", Type: "cel"}

	// ErrrulesFractionalCalculationRequiredValidation is returned when the FractionalCalculation is required but not provided.
	ErrrulesFractionalCalculationRequiredValidation = govaliderrors.ValidationError{Reason: "field FractionalCalculation is required", Path: "rules.FractionalCalculation", Type: "required"}

	// ErrrulesUseBustRequiredValidation is returned when the UseBust is required but not provided.
	ErrrulesUseBustRequiredValidation = govaliderrors.ValidationError{Reason: "field UseBust is required", Path: "rules.UseBust", Type: "required"}

	// ErrrulesUseChipRequiredValidation is returned when the UseChip is required but not provided.
	ErrrulesUseChipRequiredValidation = govaliderrors.ValidationError{Reason: "field UseChip is required", Path: "rules.UseChip", Type: "required"}
)

func Validaterules(t *rules) error {
	if t == nil {
		return ErrNilrules
	}

	var errs govaliderrors.ValidationErrors

	if t.MahjongType != domain.MahjongTypeThree && t.MahjongType != domain.MahjongTypeFour {
		err := ErrrulesMahjongTypeEnumValidation
		err.Value = t.MahjongType
		errs = append(errs, err)
	}

	if t.MahjongType == 0 {
		err := ErrrulesMahjongTypeRequiredValidation
		err.Value = t.MahjongType
		errs = append(errs, err)
	}

	if !(t.InitialPoints >= 1) {
		err := ErrrulesInitialPointsGTEValidation
		err.Value = t.InitialPoints
		errs = append(errs, err)
	}

	if t.InitialPoints == 0 {
		err := ErrrulesInitialPointsRequiredValidation
		err.Value = t.InitialPoints
		errs = append(errs, err)
	}

	if !(t.ReturnPoints >= 1) {
		err := ErrrulesReturnPointsGTEValidation
		err.Value = t.ReturnPoints
		errs = append(errs, err)
	}

	if t.ReturnPoints == 0 {
		err := ErrrulesReturnPointsRequiredValidation
		err.Value = t.ReturnPoints
		errs = append(errs, err)
	}

	if t.RankingPointsFirst == 0 {
		err := ErrrulesRankingPointsFirstRequiredValidation
		err.Value = t.RankingPointsFirst
		errs = append(errs, err)
	}

	if t.RankingPointsSecond == 0 {
		err := ErrrulesRankingPointsSecondRequiredValidation
		err.Value = t.RankingPointsSecond
		errs = append(errs, err)
	}

	if t.RankingPointsThird == 0 {
		err := ErrrulesRankingPointsThirdRequiredValidation
		err.Value = t.RankingPointsThird
		errs = append(errs, err)
	}

	if !((t.MahjongType != 2) || (t.RankingPointsFour.Valid)) {
		err := ErrrulesRankingPointsFourCELValidation
		err.Value = t.RankingPointsFour
		errs = append(errs, err)
	}

	if t.FractionalCalculation == 0 {
		err := ErrrulesFractionalCalculationRequiredValidation
		err.Value = t.FractionalCalculation
		errs = append(errs, err)
	}

	if t.UseBust == false {
		err := ErrrulesUseBustRequiredValidation
		err.Value = t.UseBust
		errs = append(errs, err)
	}

	if t.UseChip == false {
		err := ErrrulesUseChipRequiredValidation
		err.Value = t.UseChip
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*rules)(nil)

func (t *rules) Validate() error {
	return Validaterules(t)
}
