// Code generated by govalid; DO NOT EDIT.
package domain

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilGameRule is returned when the GameRule is nil.
	ErrNilGameRule = errors.New("input GameRule is nil")

	// ErrGameRuleMahjongTypeEnumValidation is the error returned when the value is not in the allowed enum values MahjongTypeThree, MahjongTypeFour.
	ErrGameRuleMahjongTypeEnumValidation = govaliderrors.ValidationError{Reason: "field MahjongType must be one of MahjongTypeThree, MahjongTypeFour", Path: "GameRule.MahjongType", Type: "enum"}

	// ErrGameRuleMahjongTypeRequiredValidation is returned when the MahjongType is required but not provided.
	ErrGameRuleMahjongTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field MahjongType is required", Path: "GameRule.MahjongType", Type: "required"}

	// ErrGameRuleInitialPointsGTEValidation is the error returned when the value of the field is less than 1.
	ErrGameRuleInitialPointsGTEValidation = govaliderrors.ValidationError{Reason: "field InitialPoints must be greater than or equal to 1", Path: "GameRule.InitialPoints", Type: "gte"}

	// ErrGameRuleInitialPointsRequiredValidation is returned when the InitialPoints is required but not provided.
	ErrGameRuleInitialPointsRequiredValidation = govaliderrors.ValidationError{Reason: "field InitialPoints is required", Path: "GameRule.InitialPoints", Type: "required"}

	// ErrGameRuleReturnPointsGTEValidation is the error returned when the value of the field is less than 1.
	ErrGameRuleReturnPointsGTEValidation = govaliderrors.ValidationError{Reason: "field ReturnPoints must be greater than or equal to 1", Path: "GameRule.ReturnPoints", Type: "gte"}

	// ErrGameRuleReturnPointsRequiredValidation is returned when the ReturnPoints is required but not provided.
	ErrGameRuleReturnPointsRequiredValidation = govaliderrors.ValidationError{Reason: "field ReturnPoints is required", Path: "GameRule.ReturnPoints", Type: "required"}

	// ErrGameRuleFractionalCalculationEnumValidation is the error returned when the value is not in the allowed enum values FractionalCalculationDecimal, FractionalCalculationRoundDown, FractionalCalculationRoundUp, FractionalCalculationRoundNearest, FractionalCalculationRoundFive.
	ErrGameRuleFractionalCalculationEnumValidation = govaliderrors.ValidationError{Reason: "field FractionalCalculation must be one of FractionalCalculationDecimal, FractionalCalculationRoundDown, FractionalCalculationRoundUp, FractionalCalculationRoundNearest, FractionalCalculationRoundFive", Path: "GameRule.FractionalCalculation", Type: "enum"}

	// ErrGameRuleFractionalCalculationRequiredValidation is returned when the FractionalCalculation is required but not provided.
	ErrGameRuleFractionalCalculationRequiredValidation = govaliderrors.ValidationError{Reason: "field FractionalCalculation is required", Path: "GameRule.FractionalCalculation", Type: "required"}
)

func ValidateGameRule(t *GameRule) error {
	if t == nil {
		return ErrNilGameRule
	}

	var errs govaliderrors.ValidationErrors

	if t.MahjongType != MahjongTypeThree && t.MahjongType != MahjongTypeFour {
		err := ErrGameRuleMahjongTypeEnumValidation
		err.Value = t.MahjongType
		errs = append(errs, err)
	}

	if t.MahjongType == 0 {
		err := ErrGameRuleMahjongTypeRequiredValidation
		err.Value = t.MahjongType
		errs = append(errs, err)
	}

	if !(t.InitialPoints >= 1) {
		err := ErrGameRuleInitialPointsGTEValidation
		err.Value = t.InitialPoints
		errs = append(errs, err)
	}

	if t.InitialPoints == 0 {
		err := ErrGameRuleInitialPointsRequiredValidation
		err.Value = t.InitialPoints
		errs = append(errs, err)
	}

	if !(t.ReturnPoints >= 1) {
		err := ErrGameRuleReturnPointsGTEValidation
		err.Value = t.ReturnPoints
		errs = append(errs, err)
	}

	if t.ReturnPoints == 0 {
		err := ErrGameRuleReturnPointsRequiredValidation
		err.Value = t.ReturnPoints
		errs = append(errs, err)
	}

	if t.FractionalCalculation != FractionalCalculationDecimal && t.FractionalCalculation != FractionalCalculationRoundDown && t.FractionalCalculation != FractionalCalculationRoundUp && t.FractionalCalculation != FractionalCalculationRoundNearest && t.FractionalCalculation != FractionalCalculationRoundFive {
		err := ErrGameRuleFractionalCalculationEnumValidation
		err.Value = t.FractionalCalculation
		errs = append(errs, err)
	}

	if t.FractionalCalculation == 0 {
		err := ErrGameRuleFractionalCalculationRequiredValidation
		err.Value = t.FractionalCalculation
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GameRule)(nil)

func (t *GameRule) Validate() error {
	return ValidateGameRule(t)
}
