// Code generated by govalid; DO NOT EDIT.
package domain

import (
	"errors"
	"unicode/utf8"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilGame is returned when the Game is nil.
	ErrNilGame = errors.New("input Game is nil")

	// ErrGameNoteMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 200.
	ErrGameNoteMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Note must have a maximum length of 200", Path: "Game.Note", Type: "maxlength"}

	// ErrGameGameRuleRequiredValidation is returned when the GameRule is required but not provided.
	ErrGameGameRuleRequiredValidation = govaliderrors.ValidationError{Reason: "field GameRule is required", Path: "Game.GameRule", Type: "required"}

	// ErrGameGameScoresMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 4.
	ErrGameGameScoresMaxItemsValidation = govaliderrors.ValidationError{Reason: "field GameScores must have a maximum of 4 items", Path: "Game.GameScores", Type: "maxitems"}

	// ErrGameGameScoresMinItemsValidation is the error returned when the length of the field is less than the minimum of 3.
	ErrGameGameScoresMinItemsValidation = govaliderrors.ValidationError{Reason: "field GameScores must have a minimum of 3 items", Path: "Game.GameScores", Type: "minitems"}

	// ErrGameGameScoresRequiredValidation is returned when the GameScores is required but not provided.
	ErrGameGameScoresRequiredValidation = govaliderrors.ValidationError{Reason: "field GameScores is required", Path: "Game.GameScores", Type: "required"}
)

func ValidateGame(t *Game) error {
	if t == nil {
		return ErrNilGame
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.Note) > 200 {
		err := ErrGameNoteMaxLengthValidation
		err.Value = t.Note
		errs = append(errs, err)
	}

	if t.GameRule == nil {
		err := ErrGameGameRuleRequiredValidation
		err.Value = t.GameRule
		errs = append(errs, err)
	}

	if len(t.GameScores) > 4 {
		err := ErrGameGameScoresMaxItemsValidation
		err.Value = t.GameScores
		errs = append(errs, err)
	}

	if len(t.GameScores) < 3 {
		err := ErrGameGameScoresMinItemsValidation
		err.Value = t.GameScores
		errs = append(errs, err)
	}

	if t.GameScores == nil {
		err := ErrGameGameScoresRequiredValidation
		err.Value = t.GameScores
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Game)(nil)

func (t *Game) Validate() error {
	return ValidateGame(t)
}
