// Code generated by govalid; DO NOT EDIT.
package domain

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilGameScore is returned when the GameScore is nil.
	ErrNilGameScore = errors.New("input GameScore is nil")

	// ErrGameScoreSeatEnumValidation is the error returned when the value is not in the allowed enum values SeatEast, SeatSouth, SeatWest, SeatNorth.
	ErrGameScoreSeatEnumValidation = govaliderrors.ValidationError{Reason: "field Seat must be one of SeatEast, SeatSouth, SeatWest, SeatNorth", Path: "GameScore.Seat", Type: "enum"}

	// ErrGameScoreSeatRequiredValidation is returned when the Seat is required but not provided.
	ErrGameScoreSeatRequiredValidation = govaliderrors.ValidationError{Reason: "field Seat is required", Path: "GameScore.Seat", Type: "required"}

	// ErrGameScoreRankingGTEValidation is the error returned when the value of the field is less than 1.
	ErrGameScoreRankingGTEValidation = govaliderrors.ValidationError{Reason: "field Ranking must be greater than or equal to 1", Path: "GameScore.Ranking", Type: "gte"}

	// ErrGameScoreRankingLTEValidation is the error returned when the value of the field is greater than 4.
	ErrGameScoreRankingLTEValidation = govaliderrors.ValidationError{Reason: "field Ranking must be less than or equal to 4", Path: "GameScore.Ranking", Type: "lte"}

	// ErrGameScoreRankingRequiredValidation is returned when the Ranking is required but not provided.
	ErrGameScoreRankingRequiredValidation = govaliderrors.ValidationError{Reason: "field Ranking is required", Path: "GameScore.Ranking", Type: "required"}
)

func ValidateGameScore(t *GameScore) error {
	if t == nil {
		return ErrNilGameScore
	}

	var errs govaliderrors.ValidationErrors

	if t.Seat != SeatEast && t.Seat != SeatSouth && t.Seat != SeatWest && t.Seat != SeatNorth {
		err := ErrGameScoreSeatEnumValidation
		err.Value = t.Seat
		errs = append(errs, err)
	}

	if t.Seat == 0 {
		err := ErrGameScoreSeatRequiredValidation
		err.Value = t.Seat
		errs = append(errs, err)
	}

	if !(t.Ranking >= 1) {
		err := ErrGameScoreRankingGTEValidation
		err.Value = t.Ranking
		errs = append(errs, err)
	}

	if !(t.Ranking <= 4) {
		err := ErrGameScoreRankingLTEValidation
		err.Value = t.Ranking
		errs = append(errs, err)
	}

	if t.Ranking == 0 {
		err := ErrGameScoreRankingRequiredValidation
		err.Value = t.Ranking
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*GameScore)(nil)

func (t *GameScore) Validate() error {
	return ValidateGameScore(t)
}
