// Code generated by govalid; DO NOT EDIT.
package domain

import (
	"errors"
	"unicode/utf8"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilGroup is returned when the Group is nil.
	ErrNilGroup = errors.New("input Group is nil")

	// ErrGroupNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 100.
	ErrGroupNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Name must have a maximum length of 100", Path: "Group.Name", Type: "maxlength"}

	// ErrGroupNameRequiredValidation is returned when the Name is required but not provided.
	ErrGroupNameRequiredValidation = govaliderrors.ValidationError{Reason: "field Name is required", Path: "Group.Name", Type: "required"}

	// ErrGroupMembersMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 10.
	ErrGroupMembersMaxItemsValidation = govaliderrors.ValidationError{Reason: "field Members must have a maximum of 10 items", Path: "Group.Members", Type: "maxitems"}

	// ErrGroupMembersRequiredValidation is returned when the Members is required but not provided.
	ErrGroupMembersRequiredValidation = govaliderrors.ValidationError{Reason: "field Members is required", Path: "Group.Members", Type: "required"}

	// ErrGroupRuleRequiredValidation is returned when the Rule is required but not provided.
	ErrGroupRuleRequiredValidation = govaliderrors.ValidationError{Reason: "field Rule is required", Path: "Group.Rule", Type: "required"}
)

func ValidateGroup(t *Group) error {
	if t == nil {
		return ErrNilGroup
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.Name) > 100 {
		err := ErrGroupNameMaxLengthValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if t.Name == "" {
		err := ErrGroupNameRequiredValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if len(t.Members) > 10 {
		err := ErrGroupMembersMaxItemsValidation
		err.Value = t.Members
		errs = append(errs, err)
	}

	if t.Members == nil {
		err := ErrGroupMembersRequiredValidation
		err.Value = t.Members
		errs = append(errs, err)
	}

	if t.Rule == nil {
		err := ErrGroupRuleRequiredValidation
		err.Value = t.Rule
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Group)(nil)

func (t *Group) Validate() error {
	return ValidateGroup(t)
}
