// Code generated by govalid; DO NOT EDIT.
package domain

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilRule is returned when the Rule is nil.
	ErrNilRule = errors.New("input Rule is nil")

	// ErrRuleMahjongTypeEnumValidation is the error returned when the value is not in the allowed enum values MahjongTypeThree, MahjongTypeFour.
	ErrRuleMahjongTypeEnumValidation = govaliderrors.ValidationError{Reason: "field MahjongType must be one of MahjongTypeThree, MahjongTypeFour", Path: "Rule.MahjongType", Type: "enum"}

	// ErrRuleMahjongTypeRequiredValidation is returned when the MahjongType is required but not provided.
	ErrRuleMahjongTypeRequiredValidation = govaliderrors.ValidationError{Reason: "field MahjongType is required", Path: "Rule.MahjongType", Type: "required"}

	// ErrRuleInitialPointsGTEValidation is the error returned when the value of the field is less than 1.
	ErrRuleInitialPointsGTEValidation = govaliderrors.ValidationError{Reason: "field InitialPoints must be greater than or equal to 1", Path: "Rule.InitialPoints", Type: "gte"}

	// ErrRuleInitialPointsRequiredValidation is returned when the InitialPoints is required but not provided.
	ErrRuleInitialPointsRequiredValidation = govaliderrors.ValidationError{Reason: "field InitialPoints is required", Path: "Rule.InitialPoints", Type: "required"}

	// ErrRuleReturnPointsGTEValidation is the error returned when the value of the field is less than 1.
	ErrRuleReturnPointsGTEValidation = govaliderrors.ValidationError{Reason: "field ReturnPoints must be greater than or equal to 1", Path: "Rule.ReturnPoints", Type: "gte"}

	// ErrRuleReturnPointsRequiredValidation is returned when the ReturnPoints is required but not provided.
	ErrRuleReturnPointsRequiredValidation = govaliderrors.ValidationError{Reason: "field ReturnPoints is required", Path: "Rule.ReturnPoints", Type: "required"}

	// ErrRuleFractionalCalculationEnumValidation is the error returned when the value is not in the allowed enum values FractionalCalculationRoundUp, FractionalCalculationRoundDown, FractionalCalculationRoundNearest, FractionalCalculationRoundUpBelowTen, FractionalCalculationRoundDownBelowTen.
	ErrRuleFractionalCalculationEnumValidation = govaliderrors.ValidationError{Reason: "field FractionalCalculation must be one of FractionalCalculationRoundUp, FractionalCalculationRoundDown, FractionalCalculationRoundNearest, FractionalCalculationRoundUpBelowTen, FractionalCalculationRoundDownBelowTen", Path: "Rule.FractionalCalculation", Type: "enum"}

	// ErrRuleFractionalCalculationRequiredValidation is returned when the FractionalCalculation is required but not provided.
	ErrRuleFractionalCalculationRequiredValidation = govaliderrors.ValidationError{Reason: "field FractionalCalculation is required", Path: "Rule.FractionalCalculation", Type: "required"}
)

func ValidateRule(t *Rule) error {
	if t == nil {
		return ErrNilRule
	}

	var errs govaliderrors.ValidationErrors

	if t.MahjongType != MahjongTypeThree && t.MahjongType != MahjongTypeFour {
		err := ErrRuleMahjongTypeEnumValidation
		err.Value = t.MahjongType
		errs = append(errs, err)
	}

	if t.MahjongType == 0 {
		err := ErrRuleMahjongTypeRequiredValidation
		err.Value = t.MahjongType
		errs = append(errs, err)
	}

	if !(t.InitialPoints >= 1) {
		err := ErrRuleInitialPointsGTEValidation
		err.Value = t.InitialPoints
		errs = append(errs, err)
	}

	if t.InitialPoints == 0 {
		err := ErrRuleInitialPointsRequiredValidation
		err.Value = t.InitialPoints
		errs = append(errs, err)
	}

	if !(t.ReturnPoints >= 1) {
		err := ErrRuleReturnPointsGTEValidation
		err.Value = t.ReturnPoints
		errs = append(errs, err)
	}

	if t.ReturnPoints == 0 {
		err := ErrRuleReturnPointsRequiredValidation
		err.Value = t.ReturnPoints
		errs = append(errs, err)
	}

	if t.FractionalCalculation != FractionalCalculationRoundUp && t.FractionalCalculation != FractionalCalculationRoundDown && t.FractionalCalculation != FractionalCalculationRoundNearest && t.FractionalCalculation != FractionalCalculationRoundUpBelowTen && t.FractionalCalculation != FractionalCalculationRoundDownBelowTen {
		err := ErrRuleFractionalCalculationEnumValidation
		err.Value = t.FractionalCalculation
		errs = append(errs, err)
	}

	if t.FractionalCalculation == 0 {
		err := ErrRuleFractionalCalculationRequiredValidation
		err.Value = t.FractionalCalculation
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*Rule)(nil)

func (t *Rule) Validate() error {
	return ValidateRule(t)
}
