-- atlas:import functions.sql
-- atlas:import games.sql
-- atlas:import groups.sql
-- atlas:import members.sql


CREATE TABLE game_scores (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id bigint NOT NULL,
  group_id bigint NOT NULL,
  member_id bigint NOT NULL,
  seat integer NOT NULL CHECK (seat BETWEEN 1 AND 4),
  ranking integer NOT NULL CHECK (ranking BETWEEN 1 AND 4),
  raw_score integer NOT NULL,
  point numeric(10, 1) NOT NULL,
  chip_count integer,
  is_busted boolean NOT NULL DEFAULT FALSE,
  created_at timestamp
  with
    time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp
  with
    time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_game_scores_game_id FOREIGN KEY (game_id) REFERENCES games (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_game_scores_group_id FOREIGN KEY (group_id) REFERENCES groups (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_game_scores_member_id FOREIGN KEY (member_id) REFERENCES members (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT uk_game_scores_game_member UNIQUE (game_id, member_id),
  CONSTRAINT uk_game_scores_game_ranking UNIQUE (game_id, ranking),
  CONSTRAINT uk_game_scores_game_seat UNIQUE (game_id, seat)
);

CREATE INDEX idx_game_scores_group_id ON game_scores(group_id);
CREATE INDEX idx_game_scores_member_id ON game_scores(member_id);

COMMENT ON COLUMN game_scores.seat IS '1: 東, 2: 南, 3: 西, 4: 北';
COMMENT ON COLUMN game_scores.ranking IS '順位';
COMMENT ON COLUMN game_scores.raw_score IS '素点 (100点単位, 例: 324 = 32,400点)';
COMMENT ON COLUMN game_scores.point IS '計算後のポイント';
COMMENT ON COLUMN game_scores.chip_count IS 'チップ枚数';
COMMENT ON COLUMN game_scores.is_busted IS '飛びフラグ';

-- updated_atの自動更新
CREATE TRIGGER on_update_time_game_scores BEFORE
UPDATE ON game_scores FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column ();

-- RLSの設定
ALTER TABLE game_scores ENABLE ROW LEVEL SECURITY;
CREATE POLICY group_policy ON game_scores FOR ALL USING (group_id = current_setting('app.group_id')::INTEGER);
