-- atlas:import functions.sql
-- atlas:import games.sql
-- atlas:import groups.sql


CREATE TABLE game_rules (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id bigint NOT NULL,
  group_id bigint NOT NULL,
  mahjong_type integer NOT NULL CHECK (mahjong_type IN (1, 2)),
  initial_points integer NOT NULL CHECK (initial_points > 0),
  return_points integer NOT NULL CHECK (return_points > 0),
  ranking_points_first integer NOT NULL,
  ranking_points_second integer NOT NULL,
  ranking_points_third integer NOT NULL,
  ranking_points_fourth integer,
  fractional_calculation integer NOT NULL CHECK (fractional_calculation IN (1, 2, 3, 4, 5)),
  fractional_recipient integer CHECK (fractional_recipient IN (1, 2)),
  use_bust boolean NOT NULL DEFAULT FALSE,
  bust_point integer,
  use_chip boolean NOT NULL DEFAULT FALSE,
  chip_point integer,
  created_at timestamp
  with
    time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp
  with
    time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_game_rules_game_id FOREIGN KEY (game_id) REFERENCES games (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_game_rules_group_id FOREIGN KEY (group_id) REFERENCES groups (id) ON UPDATE CASCADE ON DELETE CASCADE,
  -- games と 1:1
  CONSTRAINT uk_game_rules_game_id UNIQUE (game_id),
  -- ウマの合計チェック
  CONSTRAINT chk_game_rules_ranking_points CHECK (
    CASE
      WHEN mahjong_type = 1 THEN
        ranking_points_fourth IS NULL AND
        ranking_points_first + ranking_points_second + ranking_points_third = 0
      WHEN mahjong_type = 2 THEN
        ranking_points_fourth IS NOT NULL AND
        ranking_points_first + ranking_points_second + ranking_points_third + ranking_points_fourth = 0
    END
  ),
  CONSTRAINT chk_game_rules_fractional_recipient CHECK (
    (fractional_calculation = 1 AND fractional_recipient IS NULL) OR
    (fractional_calculation != 1 AND fractional_recipient IS NOT NULL)
  ),
  CONSTRAINT chk_game_rules_bust_point CHECK (
    (use_bust = TRUE AND bust_point IS NOT NULL AND bust_point > 0) OR
    (use_bust = FALSE AND bust_point IS NULL)
  ),
  CONSTRAINT chk_game_rules_chip_point CHECK (
    (use_chip = TRUE AND chip_point IS NOT NULL AND chip_point > 0) OR
    (use_chip = FALSE AND chip_point IS NULL)
  )
);

CREATE INDEX idx_game_rules_group_id ON game_rules(group_id);

COMMENT ON COLUMN game_rules.mahjong_type IS '1: 三麻, 2: 四麻';
COMMENT ON COLUMN game_rules.initial_points IS '持ち点 (単位: 千点)';
COMMENT ON COLUMN game_rules.return_points IS '返し点 (単位: 千点)';
COMMENT ON COLUMN game_rules.ranking_points_first IS '1位のウマ';
COMMENT ON COLUMN game_rules.ranking_points_second IS '2位のウマ';
COMMENT ON COLUMN game_rules.ranking_points_third IS '3位のウマ';
COMMENT ON COLUMN game_rules.ranking_points_fourth IS '4位のウマ';
COMMENT ON COLUMN game_rules.fractional_calculation IS '1: 小数点有効, 2: 切り捨て, 3: 切り上げ, 4: 四捨五入, 5: 五捨六入';
COMMENT ON COLUMN game_rules.fractional_recipient IS '1: 1位の人, 2: 最下位の人';
COMMENT ON COLUMN game_rules.use_bust IS '飛び設定';
COMMENT ON COLUMN game_rules.bust_point IS '飛び賞のポイント';
COMMENT ON COLUMN game_rules.use_chip IS 'チップ設定';
COMMENT ON COLUMN game_rules.chip_point IS 'チップのポイント';

-- updated_atの自動更新
CREATE TRIGGER on_update_time_game_rules BEFORE
UPDATE ON game_rules FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column ();

-- RLSの設定
ALTER TABLE game_rules ENABLE ROW LEVEL SECURITY;
CREATE POLICY group_policy ON game_rules FOR ALL USING (group_id = current_setting('app.group_id')::INTEGER);
