-- atlas:import functions.sql
-- atlas:import groups.sql


CREATE TABLE games (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL,
  note varchar(200) NOT NULL DEFAULT '',
  played_at timestamp
  with
    time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp
  with
    time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp
  with
    time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_games_group_id FOREIGN KEY (group_id) REFERENCES groups (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX idx_games_group_id ON games(group_id);

COMMENT ON COLUMN games.note IS '対局メモ';
COMMENT ON COLUMN games.played_at IS '対局日時';

-- updated_atの自動更新
CREATE TRIGGER on_update_time_games BEFORE
UPDATE ON games FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column ();

-- RLSの設定
ALTER TABLE games ENABLE ROW LEVEL SECURITY;
CREATE POLICY group_policy ON games FOR ALL USING (group_id = current_setting('app.group_id')::INTEGER);
