CREATE TABLE groups (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid uuid NOT NULL DEFAULT gen_random_uuid (),
  name varchar(100) NOT NULL,
  created_at timestamp
  with
    time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp
  with
    time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_groups_uid UNIQUE (uid)
);

-- updated_atの自動更新
CREATE TRIGGER on_update_time_groups BEFORE
UPDATE ON groups FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column ();
