CREATE TABLE members (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL,
  name varchar(10) NOT NULL DEFAULT ''::character varying,
  created_at timestamp
  with
    time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp
  with
    time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_members_group_id FOREIGN KEY (group_id)
        REFERENCES groups (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
  CONSTRAINT uk_members_group_id_name UNIQUE (group_id, name)
);

CREATE INDEX idx_members_group_id ON members(group_id);

-- updated_atの自動更新
CREATE TRIGGER on_update_time_members BEFORE
UPDATE ON members FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column ();

-- RLSの設定
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
CREATE POLICY group_policy ON members FOR ALL USING (group_id = current_setting('app.group_id')::INTEGER);
