CREATE TABLE rules (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL,
  mahjong_type integer NOT NULL DEFAULT 2 CHECK (mahjong_type IN (1, 2)),
  initial_points integer NOT NULL DEFAULT 25 CHECK (initial_points > 0),
  return_points integer NOT NULL DEFAULT 30 CHECK (return_points > 0),
  ranking_points_first integer NOT NULL DEFAULT 20,
  ranking_points_second integer NOT NULL DEFAULT 10,
  ranking_points_third integer NOT NULL DEFAULT -10,
  ranking_points_fourth integer,
  fractional_calculation integer NOT NULL DEFAULT 0 CHECK (fractional_calculation IN (1, 2, 3, 4, 5)),
  use_bust boolean NOT NULL DEFAULT FALSE,
  bust_point integer,
  use_chip boolean NOT NULL DEFAULT FALSE,
  chip_point integer,
  created_at timestamp
  with
    time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp
  with
    time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_members_group_id FOREIGN KEY (group_id) REFERENCES groups (id) ON UPDATE CASCADE ON DELETE CASCADE,
  -- 条件付きCHECK制約
  CONSTRAINT chk_ranking_points_by_mahjong_type CHECK (
    CASE
      WHEN mahjong_type = 1 THEN
        -- 三麻：4位はNULL、3位までの合計が0
        ranking_points_fourth IS NULL AND
        ranking_points_first + ranking_points_second + ranking_points_third = 0
      WHEN mahjong_type = 2 THEN 
        -- 四麻：4位は必須、4位までの合計が0
        ranking_points_fourth IS NOT NULL AND
        ranking_points_first + ranking_points_second + ranking_points_third + ranking_points_fourth = 0
    END
  ),
  CONSTRAINT chk_bust_point_if_use_bust CHECK (
    (use_bust = TRUE AND bust_point IS NOT NULL AND bust_point > 0) OR
    (use_bust = FALSE AND bust_point IS NULL)
  ),
  CONSTRAINT chk_chip_point_if_use_chip CHECK (
    (use_chip = TRUE AND chip_point IS NOT NULL AND chip_point > 0) OR
    (use_chip = FALSE AND chip_point IS NULL)
  )
);

CREATE INDEX idx_rules_group_id ON rules(group_id);

-- コメント
COMMENT ON COLUMN rules.mahjong_type IS '1: 三麻, 2: 四麻';
COMMENT ON COLUMN rules.initial_points IS '持ち点 (単位: 千点)';
COMMENT ON COLUMN rules.return_points IS '返し点 (単位: 千点)';
COMMENT ON COLUMN rules.ranking_points_first IS '1位のウマ';
COMMENT ON COLUMN rules.ranking_points_second IS '2位のウマ';
COMMENT ON COLUMN rules.ranking_points_third IS '3位のウマ';
COMMENT ON COLUMN rules.ranking_points_fourth IS '4位のウマ';
COMMENT ON COLUMN rules.fractional_calculation IS '1: 切り上げ, 2: 切り捨て, 3: 四捨五入, 4: 10点未満切り上げ, 5: 10点未満切り捨て';
COMMENT ON COLUMN rules.use_bust IS '飛び設定';
COMMENT ON COLUMN rules.bust_point IS '飛び賞のポイント';
COMMENT ON COLUMN rules.use_chip IS 'チップ設定';
COMMENT ON COLUMN rules.chip_point IS 'チップのポイント';

-- updated_atの自動更新
CREATE TRIGGER on_update_time_rules BEFORE
UPDATE ON rules FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column ();

-- RLSの設定
ALTER TABLE rules ENABLE ROW LEVEL SECURITY;
CREATE POLICY group_policy ON rules FOR ALL USING (group_id = current_setting('app.group_id')::INTEGER);
